OPENAI_API_KEY = "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"

# Puedes agregar más configuraciones si lo deseas
DEPARTAMENTO = "Matemáticas"
UNIVERSIDAD = "UNAL"
